# Seed completo: 48 paises x 13 laminas + especiales = ~637 laminas
# Datos: jugadores representativos actuales/historicos recientes por seleccion.
from app.database import Base, engine, SessionLocal
from app.models import User, LaminaMundial
from app.security import get_password_hash

Base.metadata.create_all(bind=engine)

# (codigo, nombre, pais, club, cantidad_repetidas, es_brillante)
LAMINAS = [

  # ══════════════════════════════════════════
  # CONCACAF
  # ══════════════════════════════════════════

  # ── CANADÁ ──
  ("CAN-01","Escudo Canadá","Canada","CSA",0,True),
  ("CAN-02","Estadio BMO Field","Canada","Toronto",0,True),
  ("CAN-03","Maxime Crépeau","Canada","LA Galaxy",0,False),
  ("CAN-04","Alphonso Davies","Canada","FC Bayern Munich",0,True),
  ("CAN-05","Kamal Miller","Canada","Inter Miami CF",0,False),
  ("CAN-06","Steven Vitória","Canada","Moreirense FC",0,False),
  ("CAN-07","Richie Larrea","Canada","Toronto FC",0,False),
  ("CAN-08","Jonathan Osorio","Canada","Toronto FC",0,False),
  ("CAN-09","Tajon Buchanan","Canada","Club Brugge",0,False),
  ("CAN-10","Jonathan David","Canada","LOSC Lille",0,True),
  ("CAN-11","Cyle Larin","Canada","Real Valladolid",0,False),
  ("CAN-12","Niko Sigur","Canada","HNK Hajduk Split",0,False),
  ("CAN-13","Derek Cornelius","Canada","Vancouver Whitecaps",0,False),

  # ── ESTADOS UNIDOS ──
  ("USA-01","Escudo Estados Unidos","Estados Unidos","US Soccer",0,True),
  ("USA-02","Estadio Rose Bowl","Estados Unidos","Pasadena",0,True),
  ("USA-03","Matt Turner","Estados Unidos","Crystal Palace",0,False),
  ("USA-04","Sergiño Dest","Estados Unidos","PSV Eindhoven",0,False),
  ("USA-05","Tim Ream","Estados Unidos","Fulham FC",0,False),
  ("USA-06","Walker Zimmermann","Estados Unidos","Nashville SC",0,False),
  ("USA-07","Weston McKennie","Estados Unidos","Juventus FC",0,False),
  ("USA-08","Tyler Adams","Estados Unidos","AFC Bournemouth",0,True),
  ("USA-09","Yunus Musah","Estados Unidos","AC Milan",0,False),
  ("USA-10","Christian Pulisic","Estados Unidos","AC Milan",0,True),
  ("USA-11","Malik Tillman","Estados Unidos","Bayer Leverkusen",0,False),
  ("USA-12","Gio Reyna","Estados Unidos","Nottingham Forest",0,False),
  ("USA-13","Haji Wright","Estados Unidos","Coventry City",0,False),

  # ── MÉXICO ──
  ("MEX-01","Escudo México","Mexico","FMF",0,True),
  ("MEX-02","Estadio Azteca","Mexico","Ciudad de Mexico",0,True),
  ("MEX-03","Guillermo Ochoa","Mexico","Salernitana",0,True),
  ("MEX-04","Jorge Sánchez","Mexico","Porto FC",0,False),
  ("MEX-05","César Montes","Mexico","Espanyol",0,False),
  ("MEX-06","Edson Álvarez","Mexico","West Ham United",0,True),
  ("MEX-07","Héctor Herrera","Mexico","Houston Dynamo",0,False),
  ("MEX-08","Orbelín Pineda","Mexico","AEK Atenas",0,False),
  ("MEX-09","Hirving Lozano","Mexico","PSV Eindhoven",0,True),
  ("MEX-10","Henry Martín","Mexico","Club América",0,False),
  ("MEX-11","Raúl Jiménez","Mexico","Fulham FC",0,False),
  ("MEX-12","Roberto Alvarado","Mexico","Chivas Guadalajara",0,False),
  ("MEX-13","Santiago Giménez","Mexico","Feyenoord",0,True),

  # ── CURAZAO ──
  ("CUR-01","Escudo Curazao","Curazao","FFK",0,True),
  ("CUR-02","Estadio Ergilio Hato","Curazao","Willemstad",0,True),
  ("CUR-03","Eloy Room","Curazao","FC Cincinnati",0,False),
  ("CUR-04","Cuco Martina","Curazao","Stoke City",0,False),
  ("CUR-05","Ethan Goss","Curazao","Jong AZ",0,False),
  ("CUR-06","Leandro Bacuna","Curazao","Reading FC",0,False),
  ("CUR-07","Cédric van der Gun","Curazao","SBV Excelsior",0,False),
  ("CUR-08","Jair Marrufo","Curazao","Independiente",0,False),
  ("CUR-09","Myron Boadu","Curazao","AS Monaco",0,True),
  ("CUR-10","Rangelo Janga","Curazao","NK Osijek",0,False),
  ("CUR-11","Gevaro Nepomuceno","Curazao","Al-Fayha",0,False),
  ("CUR-12","Jurickson Profar","Curazao","San Diego Padres",0,False),
  ("CUR-13","Daishawn Redan","Curazao","Heracles Almelo",0,False),

  # ── HAITÍ ──
  ("HAI-01","Escudo Haití","Haiti","FHF",0,True),
  ("HAI-02","Estadio Sylvio Cator","Haiti","Puerto Príncipe",0,True),
  ("HAI-03","Johny Placide","Haiti","Stade de Reims",0,False),
  ("HAI-04","Andrew Jean-Baptiste","Haiti","OGC Niza",0,False),
  ("HAI-05","Mechack Jérôme","Haiti","Portland Timbers",0,False),
  ("HAI-06","Wilde-Donald Guerrier","Haiti","Karagümrük",0,False),
  ("HAI-07","Duckens Nazon","Haiti","PAOK FC",0,False),
  ("HAI-08","Frantz Pierrot","Haiti","Motagua",0,False),
  ("HAI-09","Naomie Fecteau","Haiti","Hobro IK",0,False),
  ("HAI-10","Kervens Belfort","Haiti","Haugesund",0,False),
  ("HAI-11","Richie Zosimov","Haiti","Ethnikos Pireus",0,False),
  ("HAI-12","Steeven Saba","Haiti","Hapoel Beer Sheva",0,False),
  ("HAI-13","Jems Geffrard","Haiti","Vitória SC",0,False),

  # ── PANAMÁ ──
  ("PAN-01","Escudo Panamá","Panama","FEPAFUT",0,True),
  ("PAN-02","Estadio Rommel Fernández","Panama","Ciudad de Panamá",0,True),
  ("PAN-03","Luis Mejía","Panama","Independiente",0,False),
  ("PAN-04","Eric Davis","Panama","Columbus Crew",0,False),
  ("PAN-05","Fidel Escobar","Panama","New England Revolution",0,False),
  ("PAN-06","Roderick Miller","Panama","RB Bragantino",0,False),
  ("PAN-07","Adalberto Carrasquilla","Panama","Houston Dynamo",0,True),
  ("PAN-08","Édgar Bárcenas","Panama","Getafe CF",0,False),
  ("PAN-09","Aníbal Godoy","Panama","Nashville SC",0,False),
  ("PAN-10","Ismael Díaz","Panama","Al-Qadsiah",0,False),
  ("PAN-11","Rolando Blackburn","Panama","Inter Miami CF",0,False),
  ("PAN-12","Cecilio Waterman","Panama","Los Angeles FC",0,False),
  ("PAN-13","José Fajardo","Panama","FC Dallas",0,False),

  # ══════════════════════════════════════════
  # CONMEBOL
  # ══════════════════════════════════════════

  # ── ARGENTINA ──
  ("ARG-01","Escudo Argentina","Argentina","AFA",0,True),
  ("ARG-02","Estadio Monumental","Argentina","Buenos Aires",0,True),
  ("ARG-03","Emiliano Martínez","Argentina","Aston Villa FC",0,False),
  ("ARG-04","Cristian Romero","Argentina","Tottenham Hotspur",0,False),
  ("ARG-05","Lisandro Martínez","Argentina","Manchester United",0,False),
  ("ARG-06","Enzo Fernández","Argentina","Chelsea FC",0,False),
  ("ARG-07","Rodrigo De Paul","Argentina","Inter Miami CF",0,False),
  ("ARG-08","Alexis Mac Allister","Argentina","Liverpool FC",0,False),
  ("ARG-09","Julián Álvarez","Argentina","Atlético de Madrid",0,True),
  ("ARG-10","Lautaro Martínez","Argentina","Inter de Milán",0,True),
  ("ARG-11","Lionel Messi","Argentina","Inter Miami CF",0,True),
  ("ARG-12","Nicolás González","Argentina","Juventus FC",0,False),
  ("ARG-13","Thiago Almada","Argentina","Botafogo",0,False),

  # ── BRASIL ──
  ("BRA-01","Escudo Brasil","Brasil","CBF",0,True),
  ("BRA-02","Estadio Maracaná","Brasil","Rio de Janeiro",0,True),
  ("BRA-03","Alisson","Brasil","Liverpool FC",0,False),
  ("BRA-04","Marquinhos","Brasil","Paris Saint-Germain",0,False),
  ("BRA-05","Militão","Brasil","Real Madrid CF",0,False),
  ("BRA-06","Casemiro","Brasil","Manchester United",0,False),
  ("BRA-07","Bruno Guimarães","Brasil","Newcastle United",0,True),
  ("BRA-08","Lucas Paquetá","Brasil","West Ham United",0,False),
  ("BRA-09","Vinícius Jr.","Brasil","Real Madrid CF",0,True),
  ("BRA-10","Rodrygo","Brasil","Real Madrid CF",0,False),
  ("BRA-11","Raphinha","Brasil","FC Barcelona",0,False),
  ("BRA-12","Endrick","Brasil","Real Madrid CF",0,True),
  ("BRA-13","Neymar Jr.","Brasil","Al-Hilal SFC",0,True),

  # ── COLOMBIA ──
  ("COL-01","Escudo Colombia","Colombia","FCF",0,True),
  ("COL-02","Estadio El Campín","Colombia","Bogotá",0,True),
  ("COL-03","Camilo Vargas","Colombia","Atlas FC",0,False),
  ("COL-04","Daniel Muñoz","Colombia","Crystal Palace",0,False),
  ("COL-05","Davinson Sánchez","Colombia","Galatasaray",0,False),
  ("COL-06","Jhon Lucumí","Colombia","Bologna FC",0,False),
  ("COL-07","Mateus Uribe","Colombia","Porto FC",0,False),
  ("COL-08","Richard Ríos","Colombia","Palmeiras",0,True),
  ("COL-09","Luis Díaz","Colombia","Liverpool FC",0,True),
  ("COL-10","James Rodríguez","Colombia","Rayo Vallecano",0,True),
  ("COL-11","Radamel Falcao","Colombia","Rayo Vallecano",0,True),
  ("COL-12","Jhon Córdoba","Colombia","Krasnodar",0,False),
  ("COL-13","Jhon Durán","Colombia","Aston Villa FC",0,True),

  # ── ECUADOR ──
  ("ECU-01","Escudo Ecuador","Ecuador","FEF",0,True),
  ("ECU-02","Estadio Monumental Banco Pichincha","Ecuador","Guayaquil",0,True),
  ("ECU-03","Hernán Galíndez","Ecuador","Aucas",0,False),
  ("ECU-04","Piero Hincapié","Ecuador","Bayer Leverkusen",0,True),
  ("ECU-05","Byron Castillo","Ecuador","Liga de Quito",0,False),
  ("ECU-06","José Cifuentes","Ecuador","Los Angeles FC",0,False),
  ("ECU-07","Moisés Caicedo","Ecuador","Chelsea FC",0,True),
  ("ECU-08","Carlos Gruezo","Ecuador","Augsburg",0,False),
  ("ECU-09","Ángel Mena","Ecuador","León FC",0,False),
  ("ECU-10","Gonzalo Plata","Ecuador","Al-Qadsiah",0,False),
  ("ECU-11","Enner Valencia","Ecuador","Internacional",0,True),
  ("ECU-12","Kevin Rodríguez","Ecuador","Ipswich Town",0,False),
  ("ECU-13","Jeremy Sarmiento","Ecuador","Brighton & HA",0,False),

  # ── PARAGUAY ──
  ("PAR-01","Escudo Paraguay","Paraguay","APF",0,True),
  ("PAR-02","Estadio Defensores del Chaco","Paraguay","Asunción",0,True),
  ("PAR-03","Antony Silva","Paraguay","Libertad",0,False),
  ("PAR-04","Omar Alderete","Paraguay","Valencia CF",0,False),
  ("PAR-05","Gustavo Gómez","Paraguay","Palmeiras",0,True),
  ("PAR-06","Mathías Villasanti","Paraguay","Grêmio",0,False),
  ("PAR-07","Miguel Almirón","Paraguay","Newcastle United",0,True),
  ("PAR-08","Ángel Cardozo Lucena","Paraguay","Libertad",0,False),
  ("PAR-09","Julio Enciso","Paraguay","Brighton & HA",0,True),
  ("PAR-10","Bebelo Reynoso","Paraguay","River Plate",0,False),
  ("PAR-11","Antonio Sanabria","Paraguay","Torino FC",0,False),
  ("PAR-12","Ronaldo Dejesus","Paraguay","Fluminense",0,False),
  ("PAR-13","Ramón Sosa","Paraguay","Nottingham Forest",0,False),

  # ── URUGUAY ──
  ("URU-01","Escudo Uruguay","Uruguay","AUF",0,True),
  ("URU-02","Estadio Centenario","Uruguay","Montevideo",0,True),
  ("URU-03","Sergio Rochet","Uruguay","Inter de Milán",0,False),
  ("URU-04","Ronald Araújo","Uruguay","FC Barcelona",0,True),
  ("URU-05","José María Giménez","Uruguay","Atlético de Madrid",0,False),
  ("URU-06","Rodrigo Bentancur","Uruguay","Tottenham Hotspur",0,False),
  ("URU-07","Federico Valverde","Uruguay","Real Madrid CF",0,True),
  ("URU-08","Nicolás De La Cruz","Uruguay","River Plate",0,False),
  ("URU-09","Facundo Pellistri","Uruguay","Manchester United",0,False),
  ("URU-10","Darwin Núñez","Uruguay","Liverpool FC",0,True),
  ("URU-11","Luis Suárez","Uruguay","Inter Miami CF",0,True),
  ("URU-12","Mathías Olivera","Uruguay","Napoli",0,False),
  ("URU-13","Maximiliano Araújo","Uruguay","Sporting CP",0,False),

  # ══════════════════════════════════════════
  # UEFA
  # ══════════════════════════════════════════

  # ── ALEMANIA ──
  ("ALE-01","Escudo Alemania","Alemania","DFB",0,True),
  ("ALE-02","Estadio Allianz Arena","Alemania","Múnich",0,True),
  ("ALE-03","Marc-André ter Stegen","Alemania","FC Barcelona",0,False),
  ("ALE-04","Joshua Kimmich","Alemania","FC Bayern Munich",0,True),
  ("ALE-05","Antonio Rüdiger","Alemania","Real Madrid CF",0,False),
  ("ALE-06","Toni Kroos","Alemania","Real Madrid CF",0,True),
  ("ALE-07","Leon Goretzka","Alemania","FC Bayern Munich",0,False),
  ("ALE-08","Kai Havertz","Alemania","Arsenal FC",0,True),
  ("ALE-09","Florian Wirtz","Alemania","Liverpool FC",0,True),
  ("ALE-10","Jamal Musiala","Alemania","FC Bayern Munich",0,True),
  ("ALE-11","Serge Gnabry","Alemania","FC Bayern Munich",0,False),
  ("ALE-12","Thomas Müller","Alemania","FC Bayern Munich",0,True),
  ("ALE-13","Leroy Sané","Alemania","FC Bayern Munich",0,False),

  # ── AUSTRIA ──
  ("AUT-01","Escudo Austria","Austria","ÖFB",0,True),
  ("AUT-02","Estadio Ernst Happel","Austria","Viena",0,True),
  ("AUT-03","Patrick Pentz","Austria","Bayer Leverkusen",0,False),
  ("AUT-04","Stefan Posch","Austria","Bologna FC",0,False),
  ("AUT-05","Maximilian Wöber","Austria","Leeds United",0,False),
  ("AUT-06","Konrad Laimer","Austria","FC Bayern Munich",0,True),
  ("AUT-07","Nicolas Seiwald","Austria","RB Leipzig",0,False),
  ("AUT-08","Marcel Sabitzer","Austria","Borussia Dortmund",0,True),
  ("AUT-09","Christoph Baumgartner","Austria","RB Leipzig",0,False),
  ("AUT-10","Florian Kainz","Austria","Köln",0,False),
  ("AUT-11","Marko Arnautović","Austria","Inter de Milán",0,True),
  ("AUT-12","Michael Gregoritsch","Austria","SC Freiburg",0,False),
  ("AUT-13","Patrick Wimmer","Austria","VfB Stuttgart",0,False),

  # ── BÉLGICA ──
  ("BEL-01","Escudo Bélgica","Belgica","RBFA",0,True),
  ("BEL-02","Estadio Rey Balduino","Belgica","Bruselas",0,True),
  ("BEL-03","Koen Casteels","Belgica","Al-Qadsiah",0,False),
  ("BEL-04","Timothy Castagne","Belgica","Fulham FC",0,False),
  ("BEL-05","Wout Faes","Belgica","Leicester City",0,False),
  ("BEL-06","Axel Witsel","Belgica","Atlético de Madrid",0,False),
  ("BEL-07","Youri Tielemans","Belgica","Aston Villa FC",0,True),
  ("BEL-08","Kevin De Bruyne","Belgica","Manchester City FC",0,True),
  ("BEL-09","Leandro Trossard","Belgica","Arsenal FC",0,False),
  ("BEL-10","Romelu Lukaku","Belgica","Napoli",0,True),
  ("BEL-11","Dodi Lukebakio","Belgica","Sevilla FC",0,False),
  ("BEL-12","Lois Openda","Belgica","RB Leipzig",0,True),
  ("BEL-13","Jeremy Doku","Belgica","Manchester City FC",0,True),

  # ── BOSNIA Y HERZEGOVINA ──
  ("BIH-01","Escudo Bosnia y Herzegovina","Bosnia y Herzegovina","NFSBiH",0,True),
  ("BIH-02","Estadio Bilino Polje","Bosnia y Herzegovina","Zenica",0,True),
  ("BIH-03","Nikola Vasilj","Bosnia y Herzegovina","St. Pauli",0,False),
  ("BIH-04","Anel Ahmedhodžić","Bosnia y Herzegovina","Sheffield United",0,False),
  ("BIH-05","Ermin Bičakčić","Bosnia y Herzegovina","TSG Hoffenheim",0,False),
  ("BIH-06","Arijan Ademi","Bosnia y Herzegovina","Dinamo Zagreb",0,False),
  ("BIH-07","Miralem Pjanić","Bosnia y Herzegovina","Sharjah FC",0,True),
  ("BIH-08","Haris Hajradinović","Bosnia y Herzegovina","Konyaspor",0,False),
  ("BIH-09","Edin Džeko","Bosnia y Herzegovina","Fenerbahçe",0,True),
  ("BIH-10","Rade Krunić","Bosnia y Herzegovina","Fenerbahçe",0,False),
  ("BIH-11","Sead Kolašinac","Bosnia y Herzegovina","Atalanta",0,False),
  ("BIH-12","Vedat Muriqi","Bosnia y Herzegovina","Mallorca",0,False),
  ("BIH-13","Ermedin Demirović","Bosnia y Herzegovina","VfB Stuttgart",0,True),

  # ── CROACIA ──
  ("CRO-01","Escudo Croacia","Croacia","HNS",0,True),
  ("CRO-02","Estadio Opus Arena","Croacia","Osijek",0,True),
  ("CRO-03","Dominik Livaković","Croacia","Fenerbahçe",0,True),
  ("CRO-04","Josip Šutalo","Croacia","Ajax",0,False),
  ("CRO-05","Joško Gvardiol","Croacia","Manchester City FC",0,True),
  ("CRO-06","Luka Modrić","Croacia","Real Madrid CF",0,True),
  ("CRO-07","Marcelo Brozović","Croacia","Al-Nassr FC",0,False),
  ("CRO-08","Mateo Kovačić","Croacia","Manchester City FC",0,True),
  ("CRO-09","Ivan Perišić","Croacia","Hajduk Split",0,False),
  ("CRO-10","Andrej Kramarić","Croacia","TSG Hoffenheim",0,False),
  ("CRO-11","Bruno Petković","Croacia","Dinamo Zagreb",0,False),
  ("CRO-12","Luka Sucić","Croacia","RB Salzburg",0,True),
  ("CRO-13","Dario Šimić","Croacia","Dinamo Zagreb",0,False),

  # ── ESCOCIA ──
  ("ESC-01","Escudo Escocia","Escocia","SFA",0,True),
  ("ESC-02","Estadio Hampden Park","Escocia","Glasgow",0,True),
  ("ESC-03","Angus Gunn","Escocia","Norwich City",0,False),
  ("ESC-04","Aaron Hickey","Escocia","Brentford FC",0,False),
  ("ESC-05","Grant Hanley","Escocia","Norwich City",0,False),
  ("ESC-06","John McGinn","Escocia","Aston Villa FC",0,True),
  ("ESC-07","Callum McGregor","Escocia","Celtic FC",0,False),
  ("ESC-08","Ryan Christie","Escocia","AFC Bournemouth",0,False),
  ("ESC-09","Scott McTominay","Escocia","Napoli",0,True),
  ("ESC-10","Lyndon Dykes","Escocia","Queens Park Rangers",0,False),
  ("ESC-11","Stuart Armstrong","Escocia","Southampton",0,False),
  ("ESC-12","Billy Gilmour","Escocia","Brighton & HA",0,True),
  ("ESC-13","Ryan Porteous","Escocia","Watford",0,False),

  # ── ESPAÑA ──
  ("ESP-01","Escudo España","Espana","RFEF",0,True),
  ("ESP-02","Estadio Santiago Bernabéu","Espana","Madrid",0,True),
  ("ESP-03","Unai Simón","Espana","Athletic Club",0,False),
  ("ESP-04","Dani Carvajal","Espana","Real Madrid CF",0,False),
  ("ESP-05","Robin Le Normand","Espana","Atlético de Madrid",0,False),
  ("ESP-06","Rodri","Espana","Manchester City FC",0,True),
  ("ESP-07","Pedri","Espana","FC Barcelona",0,True),
  ("ESP-08","Fabián Ruiz","Espana","Paris Saint-Germain",0,False),
  ("ESP-09","Lamine Yamal","Espana","FC Barcelona",0,True),
  ("ESP-10","Álvaro Morata","Espana","AC Milan",0,False),
  ("ESP-11","Nico Williams","Espana","Athletic Club",0,True),
  ("ESP-12","Gavi","Espana","FC Barcelona",0,True),
  ("ESP-13","Fermín López","Espana","FC Barcelona",0,False),

  # ── FRANCIA ──
  ("FRA-01","Escudo Francia","Francia","FFF",0,True),
  ("FRA-02","Estadio de Francia","Francia","Saint-Denis",0,True),
  ("FRA-03","Mike Maignan","Francia","AC Milan",0,False),
  ("FRA-04","Jules Koundé","Francia","FC Barcelona",0,False),
  ("FRA-05","Dayot Upamecano","Francia","FC Bayern Munich",0,False),
  ("FRA-06","N'Golo Kanté","Francia","Al-Ittihad Club",0,True),
  ("FRA-07","Aurélien Tchouaméni","Francia","Real Madrid CF",0,False),
  ("FRA-08","Antoine Griezmann","Francia","Atlético de Madrid",0,True),
  ("FRA-09","Ousmane Dembélé","Francia","Paris Saint-Germain",0,False),
  ("FRA-10","Marcus Thuram","Francia","Inter de Milán",0,False),
  ("FRA-11","Kylian Mbappé","Francia","Real Madrid CF",0,True),
  ("FRA-12","Eduardo Camavinga","Francia","Real Madrid CF",0,True),
  ("FRA-13","Warren Zaïre-Emery","Francia","Paris Saint-Germain",0,True),

  # ── INGLATERRA ──
  ("ING-01","Escudo Inglaterra","Inglaterra","FA",0,True),
  ("ING-02","Estadio Wembley","Inglaterra","Londres",0,True),
  ("ING-03","Jordan Pickford","Inglaterra","Everton FC",0,False),
  ("ING-04","Kyle Walker","Inglaterra","FC Bayern Munich",0,False),
  ("ING-05","John Stones","Inglaterra","Manchester City FC",0,False),
  ("ING-06","Declan Rice","Inglaterra","Arsenal FC",0,True),
  ("ING-07","Jude Bellingham","Inglaterra","Real Madrid CF",0,True),
  ("ING-08","Phil Foden","Inglaterra","Manchester City FC",0,True),
  ("ING-09","Bukayo Saka","Inglaterra","Arsenal FC",0,True),
  ("ING-10","Harry Kane","Inglaterra","FC Bayern Munich",0,True),
  ("ING-11","Marcus Rashford","Inglaterra","Aston Villa FC",0,False),
  ("ING-12","Cole Palmer","Inglaterra","Chelsea FC",0,True),
  ("ING-13","Kobbie Mainoo","Inglaterra","Manchester United",0,True),

  # ── NORUEGA ──
  ("NOR-01","Escudo Noruega","Noruega","NFF",0,True),
  ("NOR-02","Estadio Ullevaal","Noruega","Oslo",0,True),
  ("NOR-03","Ørjan Nyland","Noruega","Nottingham Forest",0,False),
  ("NOR-04","Kristoffer Ajer","Noruega","Brentford FC",0,False),
  ("NOR-05","Leo Skiri Østigård","Noruega","Napoli",0,False),
  ("NOR-06","Sander Berge","Noruega","Fulham FC",0,False),
  ("NOR-07","Martin Ødegaard","Noruega","Arsenal FC",0,True),
  ("NOR-08","Morten Thorsby","Noruega","Genoa CFC",0,False),
  ("NOR-09","Antonio Nusa","Noruega","RB Leipzig",0,True),
  ("NOR-10","Erling Haaland","Noruega","Manchester City FC",0,True),
  ("NOR-11","Alexander Sørloth","Noruega","Atlético de Madrid",0,True),
  ("NOR-12","Ola Solbakken","Noruega","AS Roma",0,False),
  ("NOR-13","Mohamed Elyounoussi","Noruega","Celtic FC",0,False),

  # ── PAÍSES BAJOS ──
  ("NED-01","Escudo Países Bajos","Paises Bajos","KNVB",0,True),
  ("NED-02","Estadio Johan Cruyff Arena","Paises Bajos","Ámsterdam",0,True),
  ("NED-03","Bart Verbruggen","Paises Bajos","Brighton & HA",0,False),
  ("NED-04","Denzel Dumfries","Paises Bajos","Inter de Milán",0,True),
  ("NED-05","Virgil van Dijk","Paises Bajos","Liverpool FC",0,True),
  ("NED-06","Frenkie de Jong","Paises Bajos","FC Barcelona",0,True),
  ("NED-07","Tijjani Reijnders","Paises Bajos","AC Milan",0,True),
  ("NED-08","Xavi Simons","Paises Bajos","Paris Saint-Germain",0,True),
  ("NED-09","Cody Gakpo","Paises Bajos","Liverpool FC",0,True),
  ("NED-10","Memphis Depay","Paises Bajos","Atlético de Madrid",0,False),
  ("NED-11","Wout Weghorst","Paises Bajos","TSG Hoffenheim",0,False),
  ("NED-12","Ryan Gravenberch","Paises Bajos","Liverpool FC",0,True),
  ("NED-13","Brian Brobbey","Paises Bajos","Ajax",0,False),

  # ── PORTUGAL ──
  ("POR-01","Escudo Portugal","Portugal","FPF",0,True),
  ("POR-02","Estadio da Luz","Portugal","Lisboa",0,True),
  ("POR-03","Diogo Costa","Portugal","Porto FC",0,False),
  ("POR-04","João Cancelo","Portugal","FC Barcelona",0,True),
  ("POR-05","Rúben Dias","Portugal","Manchester City FC",0,True),
  ("POR-06","Rúben Neves","Portugal","Al-Hilal SFC",0,False),
  ("POR-07","Vitinha","Portugal","Paris Saint-Germain",0,True),
  ("POR-08","Bruno Fernandes","Portugal","Manchester United",0,True),
  ("POR-09","Rafael Leão","Portugal","AC Milan",0,True),
  ("POR-10","Bernardo Silva","Portugal","Manchester City FC",0,True),
  ("POR-11","Cristiano Ronaldo","Portugal","Al-Nassr FC",0,True),
  ("POR-12","Pedro Neto","Portugal","Chelsea FC",0,False),
  ("POR-13","João Félix","Portugal","Chelsea FC",0,True),

  # ── REPÚBLICA CHECA ──
  ("CZE-01","Escudo República Checa","Republica Checa","FAČR",0,True),
  ("CZE-02","Estadio Sinobo","Republica Checa","Praga",0,True),
  ("CZE-03","Jiří Staněk","Republica Checa","Sparta Praga",0,False),
  ("CZE-04","Vladimír Coufal","Republica Checa","West Ham United",0,False),
  ("CZE-05","Tomáš Holeš","Republica Checa","Slavia Praga",0,False),
  ("CZE-06","Tomáš Souček","Republica Checa","West Ham United",0,True),
  ("CZE-07","Lukáš Provod","Republica Checa","Slavia Praga",0,False),
  ("CZE-08","Antonín Barák","Republica Checa","Fiorentina",0,False),
  ("CZE-09","Patrik Schick","Republica Checa","Bayer Leverkusen",0,True),
  ("CZE-10","Ondřej Lingr","Republica Checa","Feyenoord",0,False),
  ("CZE-11","Adam Hložek","Republica Checa","Bayer Leverkusen",0,True),
  ("CZE-12","Matěj Jurásek","Republica Checa","Slavia Praga",0,False),
  ("CZE-13","Jakub Matěj Pešek","Republica Checa","RB Salzburg",0,False),

  # ── SUECIA ──
  ("SUE-01","Escudo Suecia","Suecia","SvFF",0,True),
  ("SUE-02","Estadio Friends Arena","Suecia","Solna",0,True),
  ("SUE-03","Robin Olsen","Suecia","Aston Villa FC",0,False),
  ("SUE-04","Emil Krafth","Suecia","Newcastle United",0,False),
  ("SUE-05","Isak Hien","Suecia","Atalanta",0,False),
  ("SUE-06","Albin Ekdal","Suecia","Sampdoria",0,False),
  ("SUE-07","Viktor Claesson","Suecia","FK Krasnodar",0,False),
  ("SUE-08","Emil Forsberg","Suecia","RB Leipzig",0,True),
  ("SUE-09","Dejan Kulusevski","Suecia","Tottenham Hotspur",0,True),
  ("SUE-10","Alexander Isak","Suecia","Newcastle United",0,True),
  ("SUE-11","Viktor Gyökeres","Suecia","Sporting CP",0,True),
  ("SUE-12","Mattias Svanberg","Suecia","Wolfsburg",0,False),
  ("SUE-13","Samuel Dahl","Suecia","Djurgårdens IF",0,False),

  # ── SUIZA ──
  ("SUI-01","Escudo Suiza","Suiza","SFV",0,True),
  ("SUI-02","Estadio Letzigrund","Suiza","Zúrich",0,True),
  ("SUI-03","Yann Sommer","Suiza","Inter de Milán",0,True),
  ("SUI-04","Silvan Widmer","Suiza","Mainz 05",0,False),
  ("SUI-05","Manuel Akanji","Suiza","Manchester City FC",0,True),
  ("SUI-06","Granit Xhaka","Suiza","Bayer Leverkusen",0,True),
  ("SUI-07","Remo Freuler","Suiza","Nottingham Forest",0,False),
  ("SUI-08","Xherdan Shaqiri","Suiza","Chicago Fire",0,True),
  ("SUI-09","Ruben Vargas","Suiza","Augsburg",0,False),
  ("SUI-10","Breel Embolo","Suiza","AS Monaco",0,False),
  ("SUI-11","Haris Seferović","Suiza","Galatasaray",0,False),
  ("SUI-12","Dan Ndoye","Suiza","Bologna FC",0,True),
  ("SUI-13","Zeki Amdouni","Suiza","Burnley FC",0,False),

  # ── TURQUÍA ──
  ("TUR-01","Escudo Turquía","Turquia","TFF",0,True),
  ("TUR-02","Estadio Atatürk Olímpico","Turquia","Estambul",0,True),
  ("TUR-03","Mert Günok","Turquia","Beşiktaş",0,False),
  ("TUR-04","Zeki Çelik","Turquia","AS Roma",0,False),
  ("TUR-05","Merih Demiral","Turquia","Al-Qadsiah",0,False),
  ("TUR-06","Salih Özcan","Turquia","Borussia Dortmund",0,False),
  ("TUR-07","Hakan Çalhanoğlu","Turquia","Inter de Milán",0,True),
  ("TUR-08","Kaan Ayhan","Turquia","Galatasaray",0,False),
  ("TUR-09","Kerem Aktürkoğlu","Turquia","Galatasaray",0,False),
  ("TUR-10","Yusuf Yazıcı","Turquia","LOSC Lille",0,False),
  ("TUR-11","Cenk Tosun","Turquia","Beşiktaş",0,False),
  ("TUR-12","Arda Güler","Turquia","Real Madrid CF",0,True),
  ("TUR-13","Baris Alper Yilmaz","Turquia","Galatasaray",0,False),

  # ══════════════════════════════════════════
  # CAF
  # ══════════════════════════════════════════

  # ── ARGELIA ──
  ("ALG-01","Escudo Argelia","Argelia","FAF",0,True),
  ("ALG-02","Estadio Nelson Mandela","Argelia","Argel",0,True),
  ("ALG-03","Raïs M'Bolhi","Argelia","Al-Ettifaq",0,False),
  ("ALG-04","Aissa Mandi","Argelia","LOSC Lille",0,False),
  ("ALG-05","Ramy Bensebaini","Argelia","Borussia Dortmund",0,False),
  ("ALG-06","Ismael Bennacer","Argelia","AC Milan",0,True),
  ("ALG-07","Houssem Aouar","Argelia","Al-Ittihad Club",0,False),
  ("ALG-08","Riyad Mahrez","Argelia","Al-Ahli Saudi FC",0,True),
  ("ALG-09","Youcef Atal","Argelia","OGC Niza",0,False),
  ("ALG-10","Baghdad Bounedjah","Argelia","Al-Sadd SC",0,False),
  ("ALG-11","Sofiane Feghouli","Argelia","Galatasaray",0,True),
  ("ALG-12","Said Benrahma","Argelia","Lyon",0,False),
  ("ALG-13","Amine Gouiri","Argelia","Stade Rennais",0,True),

  # ── CABO VERDE ──
  ("CPV-01","Escudo Cabo Verde","Cabo Verde","FCF",0,True),
  ("CPV-02","Estadio Adérito Sena","Cabo Verde","Mindelo",0,True),
  ("CPV-03","Vozinha","Cabo Verde","SC Farense",0,False),
  ("CPV-04","Stopira","Cabo Verde","Nantes",0,False),
  ("CPV-05","Roberto Lopes","Cabo Verde","Shamrock Rovers",0,False),
  ("CPV-06","Jamiro Monteiro","Cabo Verde","FC Nantes",0,False),
  ("CPV-07","Ryan Mendes","Cabo Verde","Panathinaikos",0,False),
  ("CPV-08","Nuno Borges","Cabo Verde","FC Arouca",0,False),
  ("CPV-09","Garry Rodrigues","Cabo Verde","Apollon Limassol",0,False),
  ("CPV-10","Hélio Varela","Cabo Verde","FC Arouca",0,False),
  ("CPV-11","Jovane Cabral","Cabo Verde","Sporting CP",0,True),
  ("CPV-12","Kenny Rocha","Cabo Verde","St. Mirren",0,False),
  ("CPV-13","Julio Tavares","Cabo Verde","FK Krasnodar",0,False),

  # ── COSTA DE MARFIL ──
  ("CIV-01","Escudo Costa de Marfil","Costa de Marfil","FIF",0,True),
  ("CIV-02","Estadio Alassane Ouattara","Costa de Marfil","Abiyán",0,True),
  ("CIV-03","Yahia Fofana","Costa de Marfil","AS Monaco",0,False),
  ("CIV-04","Serge Aurier","Costa de Marfil","Nottingham Forest",0,False),
  ("CIV-05","Eric Bailly","Costa de Marfil","Manchester United",0,False),
  ("CIV-06","Jean Michaël Seri","Costa de Marfil","Hull City",0,False),
  ("CIV-07","Franck Kessié","Costa de Marfil","FC Barcelona",0,True),
  ("CIV-08","Ibrahim Sangaré","Costa de Marfil","Nottingham Forest",0,False),
  ("CIV-09","Nicolas Pépé","Costa de Marfil","Al-Khelaifi",0,True),
  ("CIV-10","Wilfried Zaha","Costa de Marfil","Galatasaray",0,True),
  ("CIV-11","Sébastien Haller","Costa de Marfil","Borussia Dortmund",0,True),
  ("CIV-12","Simon Adingra","Costa de Marfil","Brighton & HA",0,True),
  ("CIV-13","Oumar Diakité","Costa de Marfil","Cercle Bruges",0,False),

  # ── EGIPTO ──
  ("EGY-01","Escudo Egipto","Egipto","EFA",0,True),
  ("EGY-02","Estadio Internacional de El Cairo","Egipto","El Cairo",0,True),
  ("EGY-03","Mohamed El-Shenawy","Egipto","Al-Ahly SC",0,False),
  ("EGY-04","Ahmed Hegazi","Egipto","Al-Ittihad Club",0,False),
  ("EGY-05","Omar Kamal","Egipto","Al-Ahly SC",0,False),
  ("EGY-06","Mohamed Elneny","Egipto","Arsenal FC",0,False),
  ("EGY-07","Tarek Hamed","Egipto","Zamalek SC",0,False),
  ("EGY-08","Amr El Sulaya","Egipto","Al-Ahly SC",0,False),
  ("EGY-09","Mohamed Salah","Egipto","Liverpool FC",0,True),
  ("EGY-10","Mostafa Mohamed","Egipto","Nantes",0,False),
  ("EGY-11","Omar Marmoush","Egipto","Manchester City FC",0,True),
  ("EGY-12","Ramadan Sobhi","Egipto","Al-Qadsiah",0,False),
  ("EGY-13","Mahmoud Trezeguet","Egipto","Trabzonspor",0,False),

  # ── GHANA ──
  ("GHA-01","Escudo Ghana","Ghana","GFA",0,True),
  ("GHA-02","Estadio Baba Yara","Ghana","Kumasi",0,True),
  ("GHA-03","Lawrence Ati-Zigi","Ghana","St. Gallen",0,False),
  ("GHA-04","Tariq Lamptey","Ghana","Brighton & HA",0,True),
  ("GHA-05","Daniel Amartey","Ghana","Leicester City",0,False),
  ("GHA-06","Thomas Partey","Ghana","Arsenal FC",0,True),
  ("GHA-07","Mohammed Kudus","Ghana","West Ham United",0,True),
  ("GHA-08","Iddrisu Baba","Ghana","Mallorca",0,False),
  ("GHA-09","Jordan Ayew","Ghana","Leicester City",0,False),
  ("GHA-10","Andre Ayew","Ghana","Le Havre",0,True),
  ("GHA-11","Antoine Semenyo","Ghana","AFC Bournemouth",0,True),
  ("GHA-12","Inaki Williams","Ghana","Athletic Club",0,True),
  ("GHA-13","Ernest Nuamah","Ghana","Olympique Lyon",0,True),

  # ── MARRUECOS ──
  ("MAR-01","Escudo Marruecos","Marruecos","FRMF",0,True),
  ("MAR-02","Estadio Gran Atlas","Marruecos","Marrakech",0,True),
  ("MAR-03","Yassine Bounou","Marruecos","Al-Hilal SFC",0,True),
  ("MAR-04","Achraf Hakimi","Marruecos","Paris Saint-Germain",0,True),
  ("MAR-05","Romain Saiss","Marruecos","Beşiktaş",0,False),
  ("MAR-06","Selim Amallah","Marruecos","Standard Liège",0,False),
  ("MAR-07","Azzedine Ounahi","Marruecos","Marseille",0,True),
  ("MAR-08","Sofyan Amrabat","Marruecos","Manchester United",0,True),
  ("MAR-09","Hakim Ziyech","Marruecos","Galatasaray",0,True),
  ("MAR-10","Youssef En-Nesyri","Marruecos","Fenerbahçe",0,True),
  ("MAR-11","Abdessamad Ezzalzouli","Marruecos","Betis",0,False),
  ("MAR-12","Brahim Díaz","Marruecos","Real Madrid CF",0,True),
  ("MAR-13","Munir El Haddadi","Marruecos","Al-Qadsiah",0,False),

  # ── REPÚBLICA DEMOCRÁTICA DEL CONGO ──
  ("RDC-01","Escudo RD Congo","Republica Democratica del Congo","FECOFA",0,True),
  ("RDC-02","Estadio Martyrs","Republica Democratica del Congo","Kinshasa",0,True),
  ("RDC-03","Joël Kiassumbua","Republica Democratica del Congo","Trabzonspor",0,False),
  ("RDC-04","Chancel Mbemba","Republica Democratica del Congo","Marseille",0,False),
  ("RDC-05","Ngonda Muzinga","Republica Democratica del Congo","Las Palmas",0,False),
  ("RDC-06","Samuel Bastien","Republica Democratica del Congo","Standard Liège",0,False),
  ("RDC-07","Yoane Wissa","Republica Democratica del Congo","Brentford FC",0,True),
  ("RDC-08","Cédric Bakambu","Republica Democratica del Congo","Marseille",0,False),
  ("RDC-09","Dodi Lukebakio","Republica Democratica del Congo","Sevilla FC",0,True),
  ("RDC-10","Théo Bongonda","Republica Democratica del Congo","Trabzonspor",0,False),
  ("RDC-11","Arthur Masuaku","Republica Democratica del Congo","Besiktas",0,False),
  ("RDC-12","Silas Wissa","Republica Democratica del Congo","Brentford FC",0,False),
  ("RDC-13","Emmanuel Dennis","Republica Democratica del Congo","Nottingham Forest",0,False),

  # ── SENEGAL ──
  ("SEN-01","Escudo Senegal","Senegal","FSF",0,True),
  ("SEN-02","Estadio Abdoulaye Wade","Senegal","Dakar",0,True),
  ("SEN-03","Édouard Mendy","Senegal","Al-Ahli Saudi FC",0,True),
  ("SEN-04","Youssouf Sabaly","Senegal","Real Betis",0,False),
  ("SEN-05","Kalidou Koulibaly","Senegal","Al-Hilal SFC",0,True),
  ("SEN-06","Idrissa Gueye","Senegal","Everton FC",0,False),
  ("SEN-07","Nampalys Mendy","Senegal","Leicester City",0,False),
  ("SEN-08","Ismaïla Sarr","Senegal","Crystal Palace",0,True),
  ("SEN-09","Sadio Mané","Senegal","Al-Nassr FC",0,True),
  ("SEN-10","Nicolas Jackson","Senegal","Chelsea FC",0,True),
  ("SEN-11","Iliman Ndiaye","Senegal","Everton FC",0,True),
  ("SEN-12","Pape Matar Sarr","Senegal","Tottenham Hotspur",0,True),
  ("SEN-13","Lamine Camara","Senegal","AS Monaco",0,True),

  # ── SUDÁFRICA ──
  ("RSA-01","Escudo Sudáfrica","Sudafrica","SAFA",0,True),
  ("RSA-02","Estadio FNB","Sudafrica","Johannesburgo",0,True),
  ("RSA-03","Ronwen Williams","Sudafrica","Mamelodi Sundowns",0,True),
  ("RSA-04","Siyanda Xulu","Sudafrica","Mamelodi Sundowns",0,False),
  ("RSA-05","Rushine De Reuck","Sudafrica","Mamelodi Sundowns",0,False),
  ("RSA-06","Teboho Mokoena","Sudafrica","Mamelodi Sundowns",0,True),
  ("RSA-07","Ethan Ntshumayelo","Sudafrica","Sekhukhune United",0,False),
  ("RSA-08","Themba Zwane","Sudafrica","Mamelodi Sundowns",0,True),
  ("RSA-09","Percy Tau","Sudafrica","Al-Ahly SC",0,True),
  ("RSA-10","Lyle Foster","Sudafrica","Burnley FC",0,True),
  ("RSA-11","Evidence Makgopa","Sudafrica","Orlando Pirates",0,False),
  ("RSA-12","Bongani Zungu","Sudafrica","AEK Atenas",0,False),
  ("RSA-13","Sibongiseni Mthethwa","Sudafrica","AmaZulu FC",0,False),

  # ── TÚNEZ ──
  ("TUN-01","Escudo Túnez","Tunez","FTF",0,True),
  ("TUN-02","Estadio de Radès","Tunez","Radès",0,True),
  ("TUN-03","Aymen Dahmen","Tunez","US Monastir",0,False),
  ("TUN-04","Dylan Bronn","Tunez","Salernitana",0,False),
  ("TUN-05","Montassar Talbi","Tunez","LOSC Lille",0,False),
  ("TUN-06","Aissa Laidouni","Tunez","Atlanta United",0,False),
  ("TUN-07","Ellyes Skhiri","Tunez","Eintracht Frankfurt",0,True),
  ("TUN-08","Wahbi Khazri","Tunez","Montpellier HSC",0,True),
  ("TUN-09","Seifeddine Jaziri","Tunez","Zamalek SC",0,False),
  ("TUN-10","Youssef Msakni","Tunez","Al-Arabi SC",0,True),
  ("TUN-11","Hannibal Mejbri","Tunez","Birmingham City",0,True),
  ("TUN-12","Naim Sliti","Tunez","Dijon FCO",0,False),
  ("TUN-13","Sayfallah Ltaief","Tunez","Espérance ST",0,False),

  # ══════════════════════════════════════════
  # AFC
  # ══════════════════════════════════════════

  # ── ARABIA SAUDITA ──
  ("KSA-01","Escudo Arabia Saudita","Arabia Saudita","SAFF",0,True),
  ("KSA-02","Estadio King Fahd","Arabia Saudita","Riad",0,True),
  ("KSA-03","Mohammed Al-Owais","Arabia Saudita","Al-Hilal SFC",0,True),
  ("KSA-04","Saud Abdulhamid","Arabia Saudita","AS Roma",0,True),
  ("KSA-05","Ali Al-Bulayhi","Arabia Saudita","Al-Hilal SFC",0,False),
  ("KSA-06","Abdullah Otayf","Arabia Saudita","Al-Hilal SFC",0,False),
  ("KSA-07","Salman Al-Faraj","Arabia Saudita","Al-Hilal SFC",0,True),
  ("KSA-08","Salem Al-Dawsari","Arabia Saudita","Al-Hilal SFC",0,True),
  ("KSA-09","Mohammed Kanno","Arabia Saudita","Al-Hilal SFC",0,False),
  ("KSA-10","Haitham Asiri","Arabia Saudita","Al-Ahli Saudi FC",0,False),
  ("KSA-11","Firas Al-Buraikan","Arabia Saudita","Al-Fateh SC",0,True),
  ("KSA-12","Nasser Al-Dawsari","Arabia Saudita","Al-Hilal SFC",0,False),
  ("KSA-13","Yasser Al-Shahrani","Arabia Saudita","Al-Hilal SFC",0,False),

  # ── AUSTRALIA ──
  ("AUS-01","Escudo Australia","Australia","FFA",0,True),
  ("AUS-02","Estadio ANZ","Australia","Sídney",0,True),
  ("AUS-03","Mathew Ryan","Australia","Real Sociedad",0,True),
  ("AUS-04","Milos Degenek","Australia","Red Star Belgrade",0,False),
  ("AUS-05","Harry Souttar","Australia","Leicester City",0,False),
  ("AUS-06","Jackson Irvine","Australia","St. Pauli",0,True),
  ("AUS-07","Riley McGree","Australia","Middlesbrough",0,False),
  ("AUS-08","Aziz Behich","Australia","Dundee United",0,False),
  ("AUS-09","Craig Goodwin","Australia","Adelaide United",0,False),
  ("AUS-10","Mat Leckie","Australia","Melbourne City",0,False),
  ("AUS-11","Mitchell Duke","Australia","Fagiano Okayama",0,False),
  ("AUS-12","Martin Boyle","Australia","Hibernian FC",0,False),
  ("AUS-13","Garang Kuol","Australia","Newcastle United",0,True),

  # ── CATAR ──
  ("QAT-01","Escudo Catar","Catar","QFA",0,True),
  ("QAT-02","Estadio Lusail","Catar","Lusail",0,True),
  ("QAT-03","Meshaal Barsham","Catar","Al-Sadd SC",0,False),
  ("QAT-04","Pedro Miguel","Catar","Al-Sadd SC",0,False),
  ("QAT-05","Abdelkarim Hassan","Catar","Al-Sadd SC",0,False),
  ("QAT-06","Karim Boudiaf","Catar","Al-Duhail SC",0,False),
  ("QAT-07","Assim Madibo","Catar","Al-Duhail SC",0,False),
  ("QAT-08","Akram Afif","Catar","Al-Sadd SC",0,True),
  ("QAT-09","Hassan Al-Haydos","Catar","Al-Sadd SC",0,True),
  ("QAT-10","Almoez Ali","Catar","Al-Duhail SC",0,True),
  ("QAT-11","Mohammed Muntari","Catar","Al-Duhail SC",0,False),
  ("QAT-12","Ismaeel Mohammad","Catar","Al-Sadd SC",0,False),
  ("QAT-13","Yusuf Abdurisag","Catar","Al-Ahli SC",0,False),

  # ── COREA DEL SUR ──
  ("KOR-01","Escudo Corea del Sur","Corea del Sur","KFA",0,True),
  ("KOR-02","Estadio Mundo","Corea del Sur","Seúl",0,True),
  ("KOR-03","Kim Seung-gyu","Corea del Sur","Vissel Kobe",0,False),
  ("KOR-04","Kim Moon-hwan","Corea del Sur","Jeonbuk Motors",0,False),
  ("KOR-05","Kim Min-jae","Corea del Sur","FC Bayern Munich",0,True),
  ("KOR-06","Jung Woo-young","Corea del Sur","Al-Qadsiah",0,False),
  ("KOR-07","Lee Jae-sung","Corea del Sur","Mainz 05",0,False),
  ("KOR-08","Son Heung-min","Corea del Sur","Tottenham Hotspur",0,True),
  ("KOR-09","Lee Kang-in","Corea del Sur","Paris Saint-Germain",0,True),
  ("KOR-10","Hwang Hee-chan","Corea del Sur","Wolverhampton",0,True),
  ("KOR-11","Cho Gue-sung","Corea del Sur","Celta de Vigo",0,False),
  ("KOR-12","Hwang In-beom","Corea del Sur","Vancouver Whitecaps",0,False),
  ("KOR-13","Oh Hyeon-gyu","Corea del Sur","Celtic FC",0,True),

  # ── IRAK ──
  ("IRQ-01","Escudo Irak","Irak","IFA",0,True),
  ("IRQ-02","Estadio Al-Shaab","Irak","Bagdad",0,True),
  ("IRQ-03","Jalal Hassan","Irak","Al-Zawraa SC",0,False),
  ("IRQ-04","Ali Adnan","Irak","FC Cincinnati",0,False),
  ("IRQ-05","Rebin Sulaka","Irak","Göztepe SK",0,False),
  ("IRQ-06","Amjed Attwan","Irak","Al-Quwa Al-Jawiya",0,False),
  ("IRQ-07","Saad Abdul-Amir","Irak","Al-Zawraa SC",0,False),
  ("IRQ-08","Bashar Resan","Irak","Al-Shorta SC",0,False),
  ("IRQ-09","Aymen Hussein","Irak","Al-Zawraa SC",0,True),
  ("IRQ-10","Mohanad Ali","Irak","Al-Quwa Al-Jawiya",0,False),
  ("IRQ-11","Alaa Abbas","Irak","Al-Quwa Al-Jawiya",0,False),
  ("IRQ-12","Ahmed Yasin","Irak","Wigan Athletic",0,False),
  ("IRQ-13","Shamar Nicholson","Irak","Charleroi",0,False),

  # ── IRÁN ──
  ("IRN-01","Escudo Irán","Iran","FFIRI",0,True),
  ("IRN-02","Estadio Azadi","Iran","Teherán",0,True),
  ("IRN-03","Alireza Beiranvand","Iran","Antwerp",0,True),
  ("IRN-04","Shoja Khalilzadeh","Iran","Al-Duhail SC",0,False),
  ("IRN-05","Morteza Pouraliganji","Iran","Al-Gharafa SC",0,False),
  ("IRN-06","Saeid Ezatolahi","Iran","Vejle BK",0,False),
  ("IRN-07","Ali Gholizadeh","Iran","Charleroi",0,False),
  ("IRN-08","Mehdi Torabi","Iran","Persepolis FC",0,False),
  ("IRN-09","Mehdi Taremi","Iran","Inter de Milán",0,True),
  ("IRN-10","Sardar Azmoun","Iran","Bayer Leverkusen",0,True),
  ("IRN-11","Karim Ansarifard","Iran","Nottingham Forest",0,False),
  ("IRN-12","Saman Ghoddos","Iran","AFC Bournemouth",0,False),
  ("IRN-13","Allahyar Sayyadmanesh","Iran","Fulham FC",0,True),

  # ── JAPÓN ──
  ("JPN-01","Escudo Japón","Japon","JFA",0,True),
  ("JPN-02","Estadio Nacional de Japón","Japon","Tokio",0,True),
  ("JPN-03","Shuichi Gonda","Japon","Shimizu S-Pulse",0,False),
  ("JPN-04","Hiroki Sakai","Japon","Urawa Red Diamonds",0,False),
  ("JPN-05","Maya Yoshida","Japon","FC Schalke 04",0,False),
  ("JPN-06","Wataru Endo","Japon","Liverpool FC",0,True),
  ("JPN-07","Hidemasa Morita","Japon","Sporting CP",0,True),
  ("JPN-08","Takuma Asano","Japon","VfL Bochum",0,False),
  ("JPN-09","Takefusa Kubo","Japon","Real Sociedad",0,True),
  ("JPN-10","Kaoru Mitoma","Japon","Brighton & HA",0,True),
  ("JPN-11","Ayase Ueda","Japon","Feyenoord",0,True),
  ("JPN-12","Ritsu Doan","Japon","SC Freiburg",0,True),
  ("JPN-13","Junya Ito","Japon","Stade de Reims",0,False),

  # ── JORDANIA ──
  ("JOR-01","Escudo Jordania","Jordania","JFA",0,True),
  ("JOR-02","Estadio Internacional de Ammán","Jordania","Ammán",0,True),
  ("JOR-03","Yazeed Abo Laila","Jordania","Al-Jazeera Club",0,False),
  ("JOR-04","Baha Faisal","Jordania","Al-Faisaly",0,False),
  ("JOR-05","Mousa Taamari","Jordania","Montpellier HSC",0,True),
  ("JOR-06","Saleh Hardani","Jordania","Al-Jazeera Club",0,False),
  ("JOR-07","Yazan Al-Naimat","Jordania","Al-Faisaly",0,False),
  ("JOR-08","Mahmoud Almardi","Jordania","FC Ashdod",0,False),
  ("JOR-09","Ahmad Dababneh","Jordania","Al-Ramtha SC",0,False),
  ("JOR-10","Hamza Aldarabseh","Jordania","Hatayspor",0,False),
  ("JOR-11","Musa Al-Taamari","Jordania","Montpellier HSC",0,True),
  ("JOR-12","Yaser Asprilla","Jordania","Watford",0,False),
  ("JOR-13","Nour Mansour","Jordania","FC Ashdod",0,False),

  # ── UZBEKISTÁN ──
  ("UZB-01","Escudo Uzbekistán","Uzbekistan","UFF",0,True),
  ("UZB-02","Estadio Pakhtakor","Uzbekistan","Tashkent",0,True),
  ("UZB-03","Utkir Yusupov","Uzbekistan","Lokomotiv Tashkent",0,False),
  ("UZB-04","Husayn Norchaev","Uzbekistan","Pakhtakor",0,False),
  ("UZB-05","Jasurbek Yakhshiboev","Uzbekistan","CSKA Moscú",0,False),
  ("UZB-06","Otabek Shukurov","Uzbekistan","Pakhtakor",0,False),
  ("UZB-07","Eldor Shomurodov","Uzbekistan","AS Roma",0,True),
  ("UZB-08","Dostonbek Khamdamov","Uzbekistan","Pakhtakor",0,False),
  ("UZB-09","Abbosbek Fayzullaev","Uzbekistan","CSKA Moscú",0,True),
  ("UZB-10","Jaloliddin Masharipov","Uzbekistan","Pakhtakor",0,False),
  ("UZB-11","Sherzod Nishonov","Uzbekistan","Pakhtakor",0,False),
  ("UZB-12","Ilhom Nazarov","Uzbekistan","Pakhtakor",0,False),
  ("UZB-13","Bobir Abdixoliqov","Uzbekistan","Lokomotiv Tashkent",0,False),

  # ══════════════════════════════════════════
  # OFC
  # ══════════════════════════════════════════

  # ── NUEVA ZELANDA ──
  ("NZL-01","Escudo Nueva Zelanda","Nueva Zelanda","NZF",0,True),
  ("NZL-02","Estadio Eden Park","Nueva Zelanda","Auckland",0,True),
  ("NZL-03","Stefan Marinovic","Nueva Zelanda","Vancouver Whitecaps",0,False),
  ("NZL-04","Liberato Cacace","Nueva Zelanda","Empoli FC",0,True),
  ("NZL-05","Tommy Smith","Nueva Zelanda","Indy Eleven",0,False),
  ("NZL-06","Michael Boxall","Nueva Zelanda","Minnesota United",0,False),
  ("NZL-07","Clayton Lewis","Nueva Zelanda","Vancouver Whitecaps",0,False),
  ("NZL-08","Joe Bell","Nueva Zelanda","AEK Atenas",0,False),
  ("NZL-09","Elijah Just","Nueva Zelanda","Barnsley FC",0,False),
  ("NZL-10","Chris Wood","Nueva Zelanda","Nottingham Forest",0,True),
  ("NZL-11","Callan Elliot","Nueva Zelanda","Wellington Phoenix",0,False),
  ("NZL-12","Marko Stamenic","Nueva Zelanda","FC Copenhagen",0,True),
  ("NZL-13","Matthew Garbett","Nueva Zelanda","Barnsley FC",0,False),

  # ══════════════════════════════════════════
  # ESPECIALES
  # ══════════════════════════════════════════
  ("ESP-W01","World Cup Trophy","Especiales","FIFA",0,True),
  ("ESP-W02","Golden Ball Winner - Messi","Especiales","Inter Miami CF",0,True),
  ("ESP-W03","Legend - Pelé","Especiales","Brasil",0,True),
  ("ESP-W04","Legend - Maradona","Especiales","Argentina",0,True),
  ("ESP-W05","Legend - Ronaldo R9","Especiales","Brasil",0,True),
  ("ESP-W06","Legend - Zidane","Especiales","Francia",0,True),
  ("ESP-W07","Future Star - Endrick","Especiales","Real Madrid CF",0,True),
  ("ESP-W08","Future Star - Lamine Yamal","Especiales","FC Barcelona",0,True),
  ("ESP-W09","Future Star - Kobbie Mainoo","Especiales","Manchester United",0,True),
  ("ESP-W10","Team Photo - Argentina","Especiales","AFA",0,True),
  ("ESP-W11","Team Photo - Brasil","Especiales","CBF",0,True),
  ("ESP-W12","Team Photo - Francia","Especiales","FFF",0,True),
  ("ESP-W13","Stadium Icon - Azteca","Especiales","Ciudad de México",0,True),
  ("ESP-W14","Stadium Icon - Maracaná","Especiales","Rio de Janeiro",0,True),
  ("ESP-W15","Stadium Icon - Rose Bowl","Especiales","Pasadena",0,True),
  ("ESP-W16","Captain - Messi","Especiales","Argentina",0,True),
  ("ESP-W17","Captain - Mbappé","Especiales","Francia",0,True),
  ("ESP-W18","Captain - Ronaldo","Especiales","Portugal",0,True),
  ("ESP-W19","Best Goalkeeper - Courtois","Especiales","Real Madrid CF",0,True),
  ("ESP-W20","Best Goalkeeper - Alisson","Especiales","Liverpool FC",0,True),
  ("ESP-W21","Record Breaker - Ronaldo","Especiales","Al-Nassr FC",0,True),
  ("ESP-W22","Record Breaker - Messi","Especiales","Inter Miami CF",0,True),
  ("ESP-W23","Rising Star - Lamine Yamal","Especiales","FC Barcelona",0,True),
  ("ESP-W24","Rising Star - Bellingham","Especiales","Real Madrid CF",0,True),
  ("ESP-W25","Host City - Nueva York","Especiales","USA",0,True),
  ("ESP-W26","Host City - Los Ángeles","Especiales","USA",0,True),
  ("ESP-W27","Host City - Ciudad de México","Especiales","Mexico",0,True),
  ("ESP-W28","Mascota Oficial 2026","Especiales","FIFA",0,True),
  ("ESP-W29","Balón Oficial 2026","Especiales","Adidas",0,True),
]


def seed():
    db = SessionLocal()
    try:
        if not db.query(User).filter(User.username == "admin").first():
            db.add(User(username="admin", hashed_password=get_password_hash("admin123")))
            db.commit()
            print("Usuario admin creado (password: admin123)")

        existing = db.query(LaminaMundial).count()
        if existing == 0:
            for cod, nom, pais, club, rep, brillante in LAMINAS:
                db.add(LaminaMundial(
                    codigo_lamina=cod, nombre_jugador=nom, pais=pais, club=club,
                    es_lamina_brillante=brillante,
                ))
            db.commit()
            print(f"Cargadas {len(LAMINAS)} laminas de {len(set(l[2] for l in LAMINAS))} paises/categorias")
        else:
            print(f"Ya existen {existing} laminas, no se recarga")
    finally:
        db.close()


if __name__ == "__main__":
    seed()
